### ISSUE TITLE
環境構築(takumiさん)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-wisteria#1]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by takumi-bvb** [comment]
<img width="1440" alt="スクリーンショット 2021-09-06 22 14 34" src="https://user-images.githubusercontent.com/86336792/132223372-fa2a19ec-703f-4b5d-8cbc-593b5918e5ff.png">

**Comment by yuki-tachi0219** [comment]
OKです！
これで完了といたします 👍
