### ISSUE TITLE
データ投入 Seed Products関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-wisteria#12]
db/seeds.rb にProduct関係の仮データを入れること

2人のユーザーに対して2つずつProductを作成すること。
seedを実行することで、合計4つのProductが生成されるようにすること。

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショして添付すること。

**Comment by TAKO-zhangyu** [comment]
例)
- [ ] XXXコントローラーを作成
- [ ] XXX.html.erbを作成
- [ ] コントローラーにXXXアクションを記述
- [ ] XXX.rbにXXXのバリデーションを記述

必要時間：10h

**Comment by k-akihiro1** [comment]
- [ ] ssed.rbで４つのプロダクト情報を作成（５時間）
- [ ] rails db:seedの実行、動作の確認（３時間）

必要時間：８時間
