### ISSUE TITLE
環境構築(藤井さん)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-wisteria#3]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by fujiikanji** [comment]
<img width="1188" alt="スクリーンショット 2021-09-07 17 22 04" src="https://user-images.githubusercontent.com/76743296/132311095-ced1e457-a796-4893-bf60-0ab76b6b8ae6.png">

**Comment by yuki-tachi0219** [comment]
OKです！これで完了といたします ✨
